// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqTkVbSu0ldBrZxjR8ddv1XDlQOUHHDI',
    appId: '1:670572589166:android:27831cbf459145b6c4b67f',
    messagingSenderId: '670572589166',
    projectId: 'smart-attendance-system-45653',
    storageBucket: 'smart-attendance-system-45653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrP-6y01GqqmFyFqdJmIeDdE7KLyfRXuU',
    appId: '1:670572589166:ios:f56ac4c3c048cfdbc4b67f',
    messagingSenderId: '670572589166',
    projectId: 'smart-attendance-system-45653',
    storageBucket: 'smart-attendance-system-45653.firebasestorage.app',
    iosBundleId: 'com.example.smartAttandanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTckceDXL2BQTEJPB6tZgegRUdlc0Utvo',
    appId: '1:670572589166:web:a9090cbabcb3cdb4c4b67f',
    messagingSenderId: '670572589166',
    projectId: 'smart-attendance-system-45653',
    authDomain: 'smart-attendance-system-45653.firebaseapp.com',
    storageBucket: 'smart-attendance-system-45653.firebasestorage.app',
    measurementId: 'G-P4T6MYG217',
  );
}
